resource "kubernetes_namespace_v1" "arc_system" {
  metadata {
    name = "arc-system"
  }
}

resource "kubernetes_namespace_v1" "runners" {
  metadata {
    name = var.runner_namespace
  }
}

# Referenced by the scale set via `githubConfigSecret` (pre-defined secret variation)
resource "kubernetes_secret" "github_pat" {
  metadata {
    name      = "arc-github-pat"
    namespace = kubernetes_namespace_v1.runners.metadata[0].name
  }

  data = {
    github_token = var.github_pat
  }
}

resource "helm_release" "controller" {
  name       = "gha-runner-scale-set-controller"
  namespace  = kubernetes_namespace_v1.arc_system.metadata[0].name
  repository = "oci://ghcr.io/actions/actions-runner-controller-charts"
  chart      = "gha-runner-scale-set-controller"
  version    = var.controller_chart_version
  wait       = true
}

# ARC applies scaleSetLabels only when the controller CREATES the GitHub-side
# scale set - a labels change on an existing scale set never reaches GitHub
# (k8s objects update, job matching keeps using the old labels). This trigger
# resource makes any runner_labels change plan a replacement of the helm
# release below, destroying and recreating the scale set with the new labels -
# the declarative equivalent of `tofu taint module.arc.helm_release.scale_set`.
resource "null_resource" "scale_set_labels" {
  triggers = {
    labels = join(",", var.runner_labels)
  }
}

resource "helm_release" "scale_set" {
  name       = "infersec-e2e"
  namespace  = kubernetes_namespace_v1.runners.metadata[0].name
  repository = "oci://ghcr.io/actions/actions-runner-controller-charts"
  chart      = "gha-runner-scale-set"
  version    = var.scale_set_chart_version
  wait       = true

  lifecycle {
    replace_triggered_by = [null_resource.scale_set_labels.id]
  }

  values = [
    yamlencode({
      githubConfigUrl    = "https://github.com/${var.repository}"
      githubConfigSecret = kubernetes_secret.github_pat.metadata[0].name

      scaleSetLabels = var.runner_labels
      minRunners     = var.min_runners
      maxRunners     = var.max_runners

      containerMode = {
        type = "dind"
      }

      controllerServiceAccount = {
        namespace = kubernetes_namespace_v1.arc_system.metadata[0].name
        # SA fullname generated by the controller chart for release name
        # "gha-runner-scale-set-controller" (chart 0.14.2) - the scale set chart
        # needs this exact name to bind its manager Role to the controller SA
        name = "gha-runner-scale-set-controller-gha-rs-controller"
      }

      template = {
        spec = {
          containers = [
            {
              name    = "runner"
              image   = "${var.runner_image.uri}:${var.runner_image.tag}"
              command = ["/home/runner/run.sh"]
              resources = {
                requests = {
                  cpu    = var.runner_cpu_request
                  memory = var.runner_memory_request
                }
                limits = {
                  cpu    = var.runner_cpu_limit
                  memory = var.runner_memory_limit
                }
              }
            }
          ]
        }
      }
    })
  ]

  depends_on = [
    helm_release.controller,
    kubernetes_secret.github_pat,
  ]
}
